import NextAuthSessionProvider from "../../NextAuthSessionProvider";
import "./globals.css";

export const metadata = {
  title: "AdiSoft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body>{children}</body>
      </NextAuthSessionProvider>
    </html>
  );
}
